server:
  port: 8090
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/demo3
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  output:
    ansi:
      enabled: always
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
custom:
  site:
    baseUrl: http://localhost:8090